#ifndef GUARD_GGEMS_GLOBAL_GGEMSCONFIGURATION_HH
#define GUARD_GGEMS_GLOBAL_GGEMSCONFIGURATION_HH

/*!
  \file GGEMSConfiguration.hh

  \brief This file is automatically generated by CMAKE. Don't modify it!!!

  \author Julien BERT <julien.bert@univ-brest.fr>
  \author Didier BENOIT <didier.benoit@inserm.fr>
  \author LaTIM, Brest, FRANCE
  \version 1.0
  \date Wednesday October 2, 2019
*/

#define OPENCL_KERNEL_PATH "C:/Users/dbenoit/Workspace/GGEMS_OpenCL/src/kernels"
#define GGEMS_PATH "C:/Users/dbenoit/Workspace/GGEMS_OpenCL"

#define MAXIMUM_PARTICLES 500000

#if defined _MSC_VER
#define PACKED
#else
#define PACKED __attribute__ ((__packed__))
#endif

#endif // GUARD_GGEMS_GLOBAL_GGEMSCONFIGURATION_HH
